version: 2
jobs:
  build:
    docker:
      - image: node:8.5.0
    working_directory: ~/data-hub-frontend
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn dependencies
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          name: Save yarn dependencies cache
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  lint_code:
    docker:
      - image: node:8.5.0
    working_directory: ~/data-hub-frontend
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn dependencies
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Lint code
          command: |
            mkdir -p reports
            yarn lint:all:js -- --format junit --output-file reports/eslint.xml
            yarn lint:all:styles
          when: always
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
  unit_tests:
    docker:
      - image: node:8.5.0
        environment:
          TZ: "/usr/share/zoneinfo/Europe/London"
    working_directory: ~/data-hub-frontend
    steps:
      - checkout
      - restore_cache:
          name: Restore yarn dependencies
          key: yarn-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run unit tests
          command: |
            mkdir junit
            yarn build
            yarn circle:unit
          environment:
            MOCHA_FILE: junit/test-results.xml
          when: always
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage
  user_acceptance_tests:
    docker:
      - image: ukti/docker-selenium-base:wip
        environment:
          TZ: "/usr/share/zoneinfo/Europe/London"
          REDIS_HOST: localhost
          API_ROOT: http://localhost:8000
          QA_HOST: http://localhost:3000
          QA_SELENIUM_HOST: 127.0.0.1
          QA_SELENIUM_PORT: 4444
          DATABASE_URL: postgresql://postgres@localhost/datahub
          DATAHUB_SECRET: secret
          DEBUG: 'True'
          DJANGO_SECRET_KEY: changeme
          DJANGO_SETTINGS_MODULE: config.settings.local
          ES_INDEX: test_index
          ES_URL: http://localhost:9200
          POSTGRES_URL: http://localhost:5432
          CDMS_AUTH_URL: http://example.com
          AWS_DEFAULT_REGION: eu-west-2
          AWS_ACCESS_KEY_ID: foo
          AWS_SECRET_ACCESS_KEY: bar
          DOCUMENTS_BUCKET: baz
          OMIS_NOTIFICATION_API_KEY: ''
      - image: redis:3.2.10
      - image: elasticsearch:2.3
      - image: postgres:9.5
        environment:
          POSTGRES_DB: datahub
#    parallelism: 4
#    resource_class: large
    working_directory: ~
    steps:
      - checkout
       setup data hub leeloo
      - run:
          name: Clone data hub leeloo
          command: |
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            git clone --depth 1 git@github.com:uktrade/data-hub-leeloo.git ~/app
      - restore_cache:
          name: Restore pip cache
          keys:
            - pip-dependencies-{{ checksum "~/app/requirements.txt" }}
          paths:
            - ~/cache/pip
      - run:
          name: Install pip dependencies
          command: pip install --cache-dir ~/cache/pip -r ~/app/requirements.txt
      - save_cache:
          name: Save pip cache
          key: pip-dependencies-{{ checksum "~/app/requirements.txt" }}
          paths:
            - ~/cache/pip
      - run:
          name: Configure and populate the postgres db
          command: |
            ~/app/manage.py migrate
            ~/app/manage.py loadmetadata
            ~/app/manage.py load_omis_metadata
            ~/app/manage.py createinitialrevisions
      - run:
          name: Create application
          command: |
            echo "from oauth2_provider.models import Application; from datahub.oauth.models import OAuthApplicationScope; app = Application.objects.create(name='circleci', client_id='${API_CLIENT_ID}', client_secret='${API_CLIENT_SECRET}', client_type=Application.CLIENT_CONFIDENTIAL, authorization_grant_type=Application.GRANT_PASSWORD); OAuthApplicationScope.objects.create(application=app, scopes=['internal-front-end'])" | ~/app/manage.py shell
      - run:
          name: Create test user
          command: |
            echo "from datahub.company.models import Advisor; Advisor.objects.create_user(email='${QA_USER_EMAIL}', password='${QA_USER_PASSWORD}', first_name='Circle', last_name='ci user')" | ~/app/manage.py shell
      - run:
          name: Copy leeloo .env
          command: cp ~/app/config/settings/sample.env ~/app/config/settings/.env
      - run: ~/app/manage.py loaddata ~/app/fixtures/test_data.yaml
      - run: ~/app/manage.py sync_es
      - run:
          name: Run leeloo
          command: ~/app/manage.py runserver
          background: true
      - run:
          name: Wait for postgres db, Elasticsearch and leeloo
          command: dockerize -wait ${POSTGRES_URL} -wait ${ES_URL} -wait http://localhost:8000/admin/ -timeout 60s
      # setup data hub frontend
      - restore_cache:
          name: Restore npm dependencies
          key: yarn-dependencies-{{ checksum "~/data-hub-frontend/yarn.lock" }}
      - run: yarn build
      - run:
          command: yarn start
          background: true
      - run:
          name: Wait for data hub frontend
          command: dockerize -wait ${QA_HOST}/healthcheck -timeout 60s
      - run:
          name: Split tests for parallelisation and run acceptance tests
          command: |
            # split .features for parallelisation
            FEATURES="$(circleci tests glob "~/data-hub-frontend/test/acceptance/features/**/*.feature" | circleci tests split --split-by=filesize)"

            # move groups of .features to folder
            mkdir -p ~/data-hub-frontend/test/acceptance/features_${CIRCLE_NODE_INDEX}
            for feature in ${FEATURES}; do
              mv "$feature" ~/data-hub-frontend/test/acceptance/features_${CIRCLE_NODE_INDEX}
              printf "including: $(basename "$feature")\n"
            done

            # assign .features folder name to env to pass to cucumber.js
            export FEATURES_FOLDER=/data-hub-frontend/test/acceptance/features_${CIRCLE_NODE_INDEX}
            printf "Features folder created - ${FEATURES_FOLDER}\n"

            # run acceptance tests
            mkdir -p ~/data-hub-frontend/cucumber/{reports,screenshots}
            yarn circle:acceptance
          when: always
      - run:
          name: Acceptance test reports
          command: |
            node ./data-hub-frontend/circleci/scripts/cucumber-report.js
            ./data-hub-frontend/circleci/scripts/rename-reports.sh
            ./data-hub-frontend/circleci/scripts/copy-screenshots.sh
          when: always
      - store_test_results:
          path: cucumber
      - store_artifacts:
          path: cucumber
workflows:
  version: 2
  datahub:
    jobs:
      - build
      - lint_code:
          requires:
            - build
      - unit_tests:
          requires:
            - build
      - start_uat:
          type: approval
          requires:
            - build
            - lint_code
            - unit_tests
      - user_acceptance_tests:
          requires:
            - start_uat
